const assert=require('assert'),boot=require('./boot.cjs'),w=boot(),a=w.testApp,$=id=>w.document.getElementById(id);
w.sessionStorage.setItem('atuEhrTabMode','faculty');a.setPatient('stephanie-smith');a.setView('barcodes');w.renderBarcodeCenter();const card=w.document.querySelector('[data-med-label]');assert(card);let html='';w.open=()=>({document:{write:s=>html=s,close:()=>{}}});for(const [size,width] of [['extraSmall','1.5'],['small','2'],['medium','2.625']]){card.querySelector('.medSize').value=size;card.querySelector('.printMed').click();assert(html.includes(`width:${width}in`));assert(/>\d{4}<\/text>/.test(html));}
const now=new Date(),date=`${String(now.getMonth()+1).padStart(2,'0')}/${String(now.getDate()).padStart(2,'0')}/${now.getFullYear()}`;
const content=w.renderChartDoc('Date: 02/24/2025\nDOB: 07/14/2000');assert(content.includes(date));assert(content.includes('07/14/2000'));
// Released linked orders enter the MAR; pending orders stay out.
a.setPatient('stephanie-smith');a.setView('mar');w.sessionStorage.setItem('atuEhrTabMode','student');w.renderMAR();assert(!$('view').textContent.includes('Acetaminophen'));
const order=a.state.releaseQueue.find(q=>q.chartRecordId==='admin-stephanie-acetaminophen');w.releaseItem(order.id);w.renderMAR();assert($('view').textContent.includes('Acetaminophen'));assert($('view').textContent.includes('650 mg'));
// Draft warning stops navigation when learner chooses Cancel.
a.setView('notes');w.render();$('nNarrative').value='unfinished';$('nNarrative').dispatchEvent(new w.Event('input',{bubbles:true}));w.confirm=()=>false;w.document.querySelector('aside [data-view="io"]').click();assert($('nNarrative'));assert.equal($('nNarrative').value,'unfinished');
// Named assessment fields are preserved through a redraw too.
w.clearCurrentViewDraft();a.setView('assessments');w.render();const named=w.document.querySelector('#view input[name]');if(named){named.value='draft assessment';named.dispatchEvent(new w.Event('input',{bubbles:true}));w.saveCurrentViewDraft();w.render();assert([...w.document.querySelectorAll('#view input[name]')].some(e=>e.value==='draft assessment'));}
// Jane keeps her released pre-op medications while each later medication remains separately pending.
const janeMeds=a.state.medicationCatalog.filter(m=>m.patientId==='jane-fowler'),janePending=a.state.releaseQueue.filter(q=>q.patientId==='jane-fowler'&&q.status==='pending');
for(const name of ['Lactated Ringer’s solution (LR)','Cefazolin (Ancef)','Metoclopramide (Reglan)','Midazolam (Versed)']){const med=janeMeds.find(m=>m.name===name);assert(med);assert.equal(med.releaseStatus,'released');}
assert.equal(janeMeds.find(m=>m.name==='Cefazolin (Ancef)').dose,'2 g in 250 mL');assert.equal(janeMeds.find(m=>m.name==='Metoclopramide (Reglan)').dose,'10 mg (10 mg/2 mL)');assert.equal(janeMeds.find(m=>m.name==='Midazolam (Versed)').dose,'1 mg (5 mg/mL)');
for(const name of ['Morphine sulfate (Duramorph)','Ondansetron (Zofran)','Naloxone (Narcan)','Ketorolac (Toradol)']){const med=janeMeds.find(m=>m.name===name);assert(med);assert.equal(med.releaseStatus,'pending');assert(janePending.some(q=>q.title.includes(name)));}
for(const id of ['admin-jane-respiratory-naloxone','admin-jane-respiratory-ketorolac']){const record=a.records.find(x=>x.id===id);assert(record);assert.equal(record.status,'pending');assert(janePending.some(q=>q.chartRecordId===id));}
assert.equal(janeMeds.find(m=>m.name==='Naloxone (Narcan)').dose,'0.2 mg (0.4 mg/mL)');assert.equal(janeMeds.find(m=>m.name==='Ketorolac (Toradol)').dose,'30 mg (30 mg/mL)');
w.sessionStorage.setItem('atuEhrTabMode','student');a.setPatient('jane-fowler');a.setView('mar');w.render();const janeMarText=$('view').textContent;for(const name of ['Lactated Ringer’s solution (LR)','Cefazolin (Ancef)','Metoclopramide (Reglan)','Midazolam (Versed)'])assert(janeMarText.includes(name));for(const name of ['Morphine sulfate (Duramorph)','Ondansetron (Zofran)','Naloxone (Narcan)','Ketorolac (Toradol)'])assert(!janeMarText.includes(name));
assert(!janeMeds.some(m=>m.sourceOrderId&&janeMeds.some(other=>other!==m&&!other.sourceOrderId&&other.name.split(' (')[0]===m.name.split(' (')[0])));
const janeShift2=a.records.find(r=>r.id==='chart-2d6195d201d58030b0ded95695bbcb1e');assert(janeShift2);assert.equal(janeShift2.status,'pending');assert(/Morphine sulfate \(Duramorph\).*10 mg\/mL/.test(janeShift2.content));assert(/Ondansetron \(Zofran\).*4 mg\/2 mL/.test(janeShift2.content));
assert(!a.records.some(r=>r.id==='chart-2d6195d201d58013a186edd649f28647'||r.id==='chart-form-jane-fowler'));
a.setPatient('jane-fowler');a.setView('summary');w.render();const janeSummary=$('view').textContent;
for(const removed of ['Opioid respiratory depression','Simulation complication','Patient Summary'])assert(!janeSummary.includes(removed));
const janeAdmission=a.records.find(r=>r.id==='chart-2fd195d201d58013ab8bffdf475123e4');assert(janeAdmission);assert.equal(janeAdmission.title,'History and Physical');assert.equal(janeAdmission.status,'released');assert(janeAdmission.content.includes('\n\n### Past Medical History\n\n'));assert(!janeAdmission.content.includes('<columns>'));
const janeCt=a.records.find(r=>r.id==='admin-jane-ct-results');assert(janeCt);assert.equal(janeCt.status,'released');assert(janeCt.content.includes('assets/jane-fowler-ct.png'));
assert.equal(a.state.orders.filter(x=>x.patientId==='jane-fowler'&&String(x.id).startsWith('jane-preop-')).length,15);assert(!a.state.orders.some(x=>x.patientId==='jane-fowler'&&String(x.id).startsWith('jane-postop-')));
const janeNote=a.state.notes.find(x=>x.id==='jane-admission-nursing-note-row');assert(janeNote);assert.equal(janeNote.student,'S. Escobar RN');assert(janeNote.narrative.includes('awake, alert, and oriented ×4'));
const janeBase=w.simBaseFor('jane-fowler');assert(janeBase);assert.equal(janeBase.collections.orders.filter(x=>String(x.id).startsWith('jane-preop-')).length,15);assert(!janeBase.collections.orders.some(x=>String(x.id).startsWith('jane-postop-')));assert(janeBase.collections.notes.some(x=>x.id==='jane-admission-nursing-note-row'));assert(janeBase.chartRecords.some(x=>x.id==='admin-jane-ct-results'&&x.status==='released'));
assert(!a.records.some(r=>r.id==='chart-2d6195d201d580a19062cdbe1706684f'));
w.sessionStorage.setItem('atuEhrTabMode','student');a.setView('labs');w.render();assert($('view').textContent.includes('CT Abdomen and Pelvis'));assert($('view').querySelector('img[src="assets/jane-fowler-ct.png"]'));
a.setView('notes');w.render();assert($('view').textContent.includes('Admission to 211E'));assert($('view').textContent.includes('S. Escobar RN'));
w.sessionStorage.setItem('atuEhrTabMode','student');a.setView('surgery');w.render();assert($('jpf-procedure'));assert(!/Current Scenario Stage|Scenario Progression|Pain \/ Medication Decision|Respiratory Depression/.test($('view').textContent));
w.sessionStorage.setItem('atuEhrTabMode','faculty');w.render();assert($('view').textContent.includes('Current Scenario Stage:'));assert($('view').textContent.includes('Scenario Progression'));assert($('jpc-identifiers'));assert($('jpc-surgicalConsent'));assert($('jpc-jewelry'));assert($('jpf-readiness'));assert.equal($('jpf-lastSolid').type,'datetime-local');assert.equal($('jpf-lastClearLiquids').type,'datetime-local');
$('janeChecklistStudent').value='RN Test';$('jpc-identifiers').checked=true;$('jpf-procedure').value='Matches patient statement, consent, and schedule';$('jpf-readiness').value='Ready for OR';$('saveJaneChecklist').click();
const savedChecklist=a.state.surgicalChecklist.find(x=>x.patientId==='jane-fowler');assert(savedChecklist);assert(savedChecklist.checks.identifiers);assert.equal(savedChecklist.fields.readiness,'Ready for OR');assert.equal(savedChecklist.student,'RN Test');
w.renderSurgery();assert.equal($('jpf-readiness').value,'Ready for OR');assert($('jpc-identifiers').checked);
// Packet audit: current demographics, clinical progression, generic/brand medication names, and release status.
const packetIds=['amelia-sung','jane-fowler','fatima-sanogo','molly-thomas'];
for(const id of packetIds)for(const med of a.state.medicationCatalog.filter(x=>x.patientId===id))assert(/\([^()]+\)/.test(med.name),`${id}: generic/brand pair missing for ${med.name}`);
const amelia=a.state.patients.find(x=>x.id==='amelia-sung');assert.equal(amelia.weightKg,83);assert.deepEqual(amelia.allergies,['Shellfish','Penicillin']);assert.equal(amelia.gbs,'Positive');assert.equal(amelia.primaryDiagnosis,'Active labor / gestational diabetes');
for(const name of ['Oxytocin (Pitocin)','Lactated Ringer’s solution (LR)','Clindamycin (Cleocin)','Morphine sulfate (Duramorph)','Lidocaine (Xylocaine) 1%'])assert.equal(a.state.medicationCatalog.find(x=>x.patientId==='amelia-sung'&&x.name===name)?.releaseStatus,'released');
assert(!a.state.medicationCatalog.some(x=>x.patientId==='amelia-sung'&&/Hydromorphone/i.test(x.name)));assert(a.state.orders.some(x=>x.patientId==='amelia-sung'&&/Clindamycin.*GBS prophylaxis/i.test(x.text)));
assert(a.records.find(x=>x.id==='packet-amelia-shift2')?.content.includes('Apgar: 1 minute = 2; 5 minutes = 7'));
const fatima=a.state.patients.find(x=>x.id==='fatima-sanogo');assert.equal(fatima.fetus,'Male');assert.equal(fatima.weightKg,71);assert(a.records.find(x=>x.id==='chart-256195d201d581d78298cd4150f3424f')?.content.includes('Placenta manually delivered intact at 1235'));
for(const name of ['Methylergonovine (Methergine)','Carboprost tromethamine (Hemabate)','Misoprostol (Cytotec)','Tranexamic acid (Cyklokapron; TXA)'])assert.equal(a.state.medicationCatalog.find(x=>x.patientId==='fatima-sanogo'&&x.name===name)?.releaseStatus,'pending');
for(const name of ['Racepinephrine (Asthmanefrin)','Dexamethasone (Decadron)','Ampicillin (Principen)','Dextrose 5% in 0.45% sodium chloride (D5 1/2 NS)'])assert.equal(a.state.medicationCatalog.find(x=>x.patientId==='molly-thomas'&&x.name===name)?.releaseStatus,'pending');
assert.equal(a.state.medicationCatalog.find(x=>x.patientId==='molly-thomas'&&x.name==='Sodium chloride 0.9% (Normal Saline)')?.releaseStatus,'released');
for(const retired of ['chart-283195d201d5808bbeb5e24d75f4d33f','chart-28b195d201d5805ca4d1c8978c9278be','chart-284195d201d581908c27c50dbf996e0f'])assert(!a.records.some(x=>x.id===retired));
for(const id of ['fatima-sanogo','molly-thomas','stephanie-smith']){a.setPatient(id);a.setView('summary');w.render();assert(w.document.querySelector('aside [data-view="glucose"]').classList.contains('hiddenByPatient'));a.setView('glucose');w.render();assert.equal(w.document.querySelector('aside button.active')?.dataset.view,'summary');assert(!a.state.glucoseChecks.some(x=>x.patientId===id));assert(!a.state.medicationCatalog.some(x=>x.patientId===id&&/insulin/i.test(x.name)));assert(!a.state.orders.some(x=>x.patientId===id&&/glucose checks?|blood sugar|sliding[- ]scale|insulin/i.test(x.text||'')));a.setView('flowsheets');w.render();assert(!$('vBG'));assert(!$('view').textContent.includes('Blood Glucose'));}
a.setPatient('charles-jones');a.setView('summary');w.render();assert(!w.document.querySelector('aside [data-view="glucose"]').classList.contains('hiddenByPatient'));
console.log('PASS: labels/codes/dates/drafts; packet content, generic/brand medications, release states, Jane cleanup, and interactive pre-op checklist.');setTimeout(()=>w.close(),200);
